# Generated by Django 3.0 on 2020-04-21 12:13

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20200415_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=bboard.models.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
