# Generated by Django 3.0 on 2020-04-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_auto_20200421_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
