# Generated by Django 3.0 on 2020-04-23 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_auto_20200423_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bd',
            name='img',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Объявление', to='bboard.Bd')),
            ],
        ),
    ]
